--INSERTs generated by GenerateInsert (Build 6)
--Project page: http://github.com/drumsta/sql-generate-insert
SET NOCOUNT ON
INSERT INTO dbo.LoginUserData
([FirstName],[LastName],[Email],[Password],[LastDateLogged])
VALUES
 ('Jefferson','Nicholas','nicholas.jefferson@domain.com','password1',CONVERT(datetime,NULL,121))
,('Thomas','Claudio','claudio.thomas@domain.com','password2',CONVERT(datetime,NULL,121))
,('Steven','Paolo','steven.paolo@domain.com','password3',CONVERT(datetime,NULL,121))
,('Billy','Walsh','billy.walsh@domain.com','password4',CONVERT(datetime,NULL,121))